newContentEditor: nvim

baseURL: https://bdcaf.github.io/r-hugo-papercss-template/
languageCode: en-us
defaultContentLanguage: en
theme: papercss-hugo-theme
title: R Hugo Papercss site template

publishDir: gh-pages

taxonomies:
  tag: tags

imaging:
  quality: 99


params:
  homeMetaContent: A template site for using hugo with papercss theme and knitr r for enjoyable stat blogging.
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006

mediaTypes:
  "text/plain":
    suffixes:
      - md
      - rmd

#outputs:
  #page:
    #- html
    #- md

#outputFormats:
  #md:
    #mediaType: "text/plain"
    #isPlainText: true

ignoreFiles:
  - "source.md$"
